name: Update README with Proposal Links

on:
  push:
    branches:
      - master
    paths:
      - 'proposals/**'
      - 'scripts/generate_readme.rs'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Ensures history is available for pushes

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Generate README
      run: |
        rustc scripts/generate_readme.rs -o generate_readme
        ./generate_readme

    - name: Commit and Push README.md
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Automatically update README with proposals" || exit 0
        git push
